version: '3'
services:
    mysql:
        container_name: ivet_db
        image: mysql:5.6
        ports:
            - 3306:3306
        restart: always
        volumes:
            - ./db:/var/lib/mysql
            - ./ivetune_geral:/docker-entrypoint-initdb.d
        command: 
            [
                --default-authentication-plugin=mysql_native_password
            ]
        environment: 
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_DATABASE: ivetune_geral
            MYSQL_USER: user
            MYSQL_PASSWORD: pass
        
    php:
        build:
            context: .
            dockerfile: Dockerfile
        depends_on:
            - mysql
        volumes:
            - ./public_html:/var/www/html
        ports:
            - 80:80
        links:
            - mysql
volumes:
    mysql_data:
